stages:
  - test
  - build
  - deploy

variables:
  # Definisi variabel global di sini
  POSTGRES_DB: db_hw_week11
  DOCKER_IMAGE: inalmahpud1/homework-prisma-postgres-api:1.0 # Ganti dengan informasi gambar Anda

# Job untuk menguji kode
test:
  stage: test
  script:
    npm run test

# Job untuk membangun aplikasi dan gambar Docker
build:
  stage: build
  script:
    - echo "Building the application..."
    # Lakukan langkah-langkah build aplikasi Anda di sini
    - docker build -t $DOCKER_IMAGE .

# Job untuk mengirim gambar Docker ke Docker Hub
deploy:
  stage: deploy
  only:
    - master # Hanya jalankan ketika ada perubahan pada branch master
  script:
    - echo "Deploying to Docker Hub..."
    - docker login --username=$DH_USERNAME --password=$DH_PASSWORD
    - docker push $DOCKER_IMAGE

# Job lainnya...
# Anda bisa menambahkan lebih banyak job sesuai kebutuhan Anda
