image: node:18-alpine
variables:
  REPOSITORY_URL: inalmahpud1/homework-prisma-postgres-api:1.0

services:
  - docker:dind

before_script:
  - docker login -u $DH_USERNAME -p $DH_PASSWORD

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Build image..."
    - docker build \
      -t homework-prisma-postgres-api:1.0 \
      --build-arg PORT=$PORT \
      --no-cache .
    - echo "Tagging image..."
    - docker tag homework-prisma-postgres-api:1.0 $REPOSITORY_URL
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker stop homework-prisma-postgres-api || true
    - docker rm homework-prisma-postgres-api || true
    - docker run -dt -p $PORT:$PORT --name homework-prisma-postgres-api $REPOSITORY_URL
    - docker image prune -f
  only:
    - master
