version: "3.9"
networks:
  app-network:
   driver: bridge
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_hw_week11
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  prisma-postgres-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-postgres-api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app-network

volumes:
  postgres-data: